name: "Node Setup & Lint"
description: "Reusable action to setup Node.js and run lint"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install
      shell: bash  # <-- ADD THIS

    - name: Run ESLint
      run: npm run lint
      shell: bash  # <-- ADD THIS
