name: Daily Dependency Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual run

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: |
          npm audit --json > audit.json
          cat audit.json

      - name: Create issue if vulnerabilities found
        if: failure() # runs only if previous step fails
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Dependency Vulnerability Found"
          content-filepath: audit.json
